/**
 * Chat models for TubeLight.
 * These model IDs should match the enabled model IDs inside:
 * InsForge → Model Gateway.
 */

export const CHAT_MODEL_OPTIONS = [
  // --------------------
  // OpenAI
  // --------------------
  {
    id: 'openai/gpt-5.4-image-2',
    label: 'GPT 5.4 Image 2',
    provider: 'OpenAI',
    input: 'Text / Image',
    output: 'Text / Image',
    inputPrice: '$8.0 / M tokens',
    outputPrice: '$15.0 / M tokens',
    blurb: 'Advanced multimodal OpenAI model for text and image input/output.',
  },
  {
    id: 'openai/gpt-4o',
    label: 'GPT 4o',
    provider: 'OpenAI',
    input: 'Text / Image',
    output: 'Text',
    inputPrice: '$2.5 / M tokens',
    outputPrice: '$10.0 / M tokens',
    blurb: 'Fast multimodal OpenAI model for text and image input.',
  },
  {
    id: 'openai/gpt-5.4',
    label: 'GPT 5.4',
    provider: 'OpenAI',
    input: 'Text / Image',
    output: 'Text',
    inputPrice: '$2.5 / M tokens',
    outputPrice: '$15.0 / M tokens',
    blurb: 'High-capability OpenAI model for advanced chat and reasoning.',
  },
  {
    id: 'openai/gpt-5.2',
    label: 'GPT 5.2',
    provider: 'OpenAI',
    input: 'Text / Image',
    output: 'Text',
    inputPrice: '$1.8 / M tokens',
    outputPrice: '$14.0 / M tokens',
    blurb: 'OpenAI model for general chat, reasoning, and multimodal input.',
  },
  {
    id: 'openai/gpt-5.2-codex',
    label: 'GPT 5.2 Codex',
    provider: 'OpenAI',
    input: 'Text / Image',
    output: 'Text',
    inputPrice: '$1.8 / M tokens',
    outputPrice: '$14.0 / M tokens',
    blurb: 'Coding-focused OpenAI model for programming and technical tasks.',
  },
  {
    id: 'openai/gpt-5',
    label: 'GPT 5',
    provider: 'OpenAI',
    input: 'Text / Image',
    output: 'Text',
    inputPrice: '$1.3 / M tokens',
    outputPrice: '$10.0 / M tokens',
    blurb: 'General-purpose OpenAI model for everyday chat and reasoning.',
  },
  {
    id: 'openai/gpt-5-mini',
    label: 'GPT 5 Mini',
    provider: 'OpenAI',
    input: 'Text / Image',
    output: 'Text',
    inputPrice: '$0.25 / M tokens',
    outputPrice: '$2.0 / M tokens',
    blurb: 'Low-cost OpenAI model for fast and efficient responses.',
  },
  {
    id: 'openai/gpt-4o-mini',
    label: 'GPT 4o Mini',
    provider: 'OpenAI',
    input: 'Text / Image',
    output: 'Text',
    inputPrice: '$0.15 / M tokens',
    outputPrice: '$0.60 / M tokens',
    blurb: 'Fast and affordable OpenAI model for lightweight chat tasks.',
  },

  // --------------------
  // Anthropic
  // --------------------
  {
    id: 'anthropic/claude-opus-4.1',
    label: 'Claude Opus 4.1',
    provider: 'Anthropic',
    input: 'Text / Image',
    output: 'Text',
    inputPrice: '$15.0 / M tokens',
    outputPrice: '$75.0 / M tokens',
    blurb: 'Premium Anthropic model for complex reasoning and writing.',
  },
  {
    id: 'anthropic/claude-opus-4.5',
    label: 'Claude Opus 4.5',
    provider: 'Anthropic',
    input: 'Text / Image',
    output: 'Text',
    inputPrice: '$5.0 / M tokens',
    outputPrice: '$25.0 / M tokens',
    blurb: 'Advanced Anthropic Opus model for high-quality reasoning.',
  },
  {
    id: 'anthropic/claude-opus-4.6',
    label: 'Claude Opus 4.6',
    provider: 'Anthropic',
    input: 'Text / Image',
    output: 'Text',
    inputPrice: '$5.0 / M tokens',
    outputPrice: '$25.0 / M tokens',
    blurb: 'High-capability Claude Opus model for advanced tasks.',
  },
  {
    id: 'anthropic/claude-sonnet-4',
    label: 'Claude Sonnet 4',
    provider: 'Anthropic',
    input: 'Text / Image',
    output: 'Text',
    inputPrice: '$3.0 / M tokens',
    outputPrice: '$15.0 / M tokens',
    blurb: 'Balanced Anthropic Sonnet model for writing, reasoning, and chat.',
  },
  {
    id: 'anthropic/claude-sonnet-4.5',
    label: 'Claude Sonnet 4.5',
    provider: 'Anthropic',
    input: 'Text / Image',
    output: 'Text',
    inputPrice: '$3.0 / M tokens',
    outputPrice: '$15.0 / M tokens',
    blurb: 'Strong Claude Sonnet model for reasoning, writing, and coding.',
  },
  {
    id: 'anthropic/claude-sonnet-4.6',
    label: 'Claude Sonnet 4.6',
    provider: 'Anthropic',
    input: 'Text / Image',
    output: 'Text',
    inputPrice: '$3.0 / M tokens',
    outputPrice: '$15.0 / M tokens',
    blurb: 'Updated Claude Sonnet model for multimodal input and text output.',
  },
  {
    id: 'anthropic/claude-haiku-4.5',
    label: 'Claude Haiku 4.5',
    provider: 'Anthropic',
    input: 'Text / Image',
    output: 'Text',
    inputPrice: '$1.0 / M tokens',
    outputPrice: '$5.0 / M tokens',
    blurb: 'Fast Anthropic model for lightweight chat and quick answers.',
  },
  {
    id: 'anthropic/claude-3.5-haiku',
    label: 'Claude 3.5 Haiku',
    provider: 'Anthropic',
    input: 'Text / Image',
    output: 'Text',
    inputPrice: '$0.80 / M tokens',
    outputPrice: '$4.0 / M tokens',
    blurb: 'Efficient Claude Haiku model for fast and affordable responses.',
  },

  // --------------------
  // Google
  // --------------------
  {
    id: 'google/gemini-3-pro-image-preview',
    label: 'Gemini 3 Pro Image Preview',
    provider: 'Google',
    input: 'Text / Image',
    output: 'Text / Image',
    inputPrice: '$2.0 / M tokens',
    outputPrice: '$12.0 / M tokens',
    blurb: 'Google Gemini model with text and image input/output support.',
  },
  {
    id: 'google/gemini-3.1-pro-preview',
    label: 'Gemini 3.1 Pro Preview',
    provider: 'Google',
    input: 'Text / Image / Audio',
    output: 'Text',
    inputPrice: '$2.0 / M tokens',
    outputPrice: '$12.0 / M tokens',
    blurb: 'Google Gemini Pro preview model for multimodal input.',
  },
  {
    id: 'google/gemini-2.5-pro',
    label: 'Gemini 2.5 Pro',
    provider: 'Google',
    input: 'Text / Image / Audio',
    output: 'Text',
    inputPrice: '$1.3 / M tokens',
    outputPrice: '$10.0 / M tokens',
    blurb: 'Google Gemini Pro model for advanced multimodal understanding.',
  },
  {
    id: 'google/gemini-3-flash-preview',
    label: 'Gemini 3 Flash Preview',
    provider: 'Google',
    input: 'Text / Image / Audio',
    output: 'Text',
    inputPrice: '$0.50 / M tokens',
    outputPrice: '$3.0 / M tokens',
    blurb: 'Fast Gemini preview model for multimodal chat.',
  },
  {
    id: 'google/gemini-2.0-flash-001',
    label: 'Gemini 2.0 Flash 001',
    provider: 'Google',
    input: 'Text / Image / Audio',
    output: 'Text',
    inputPrice: '$0.10 / M tokens',
    outputPrice: '$0.40 / M tokens',
    blurb: 'Fast and low-cost Gemini model for multimodal input.',
  },
  {
    id: 'google/gemini-2.5-flash-lite',
    label: 'Gemini 2.5 Flash Lite',
    provider: 'Google',
    input: 'Text / Image / Audio',
    output: 'Text',
    inputPrice: '$0.10 / M tokens',
    outputPrice: '$0.40 / M tokens',
    blurb: 'Lightweight Gemini Flash model for fast responses.',
  },

  // --------------------
  // DeepSeek
  // --------------------
  {
    id: 'deepseek/deepseek-r1',
    label: 'DeepSeek R1',
    provider: 'DeepSeek',
    input: 'Text',
    output: 'Text',
    inputPrice: '$0.70 / M tokens',
    outputPrice: '$2.5 / M tokens',
    blurb: 'DeepSeek reasoning model for complex thinking tasks.',
  },
  {
    id: 'deepseek/deepseek-v4-pro',
    label: 'DeepSeek V4 Pro',
    provider: 'DeepSeek',
    input: 'Text',
    output: 'Text',
    inputPrice: '$0.43 / M tokens',
    outputPrice: '$0.87 / M tokens',
    blurb: 'Advanced DeepSeek model for high-quality text generation.',
  },
  {
    id: 'deepseek/deepseek-chat',
    label: 'DeepSeek Chat',
    provider: 'DeepSeek',
    input: 'Text',
    output: 'Text',
    inputPrice: '$0.32 / M tokens',
    outputPrice: '$0.89 / M tokens',
    blurb: 'General-purpose DeepSeek chat model.',
  },
  {
    id: 'deepseek/deepseek-v3.2-exp',
    label: 'DeepSeek V3.2 Exp',
    provider: 'DeepSeek',
    input: 'Text',
    output: 'Text',
    inputPrice: '$0.27 / M tokens',
    outputPrice: '$0.41 / M tokens',
    blurb: 'Experimental DeepSeek model for text generation.',
  },
  {
    id: 'deepseek/deepseek-v3.2',
    label: 'DeepSeek V3.2',
    provider: 'DeepSeek',
    input: 'Text',
    output: 'Text',
    inputPrice: '$0.25 / M tokens',
    outputPrice: '$0.38 / M tokens',
    blurb: 'Efficient DeepSeek model for text-based chat.',
  },
  {
    id: 'deepseek/deepseek-v4-flash',
    label: 'DeepSeek V4 Flash',
    provider: 'DeepSeek',
    input: 'Text',
    output: 'Text',
    inputPrice: '$0.14 / M tokens',
    outputPrice: '$0.28 / M tokens',
    blurb: 'Fast and low-cost DeepSeek model.',
  },

  // --------------------
  // Qwen
  // --------------------
  {
    id: 'qwen/qwen3-vl-235b-a22b-instruct',
    label: 'Qwen3 VL 235B A22B Instruct',
    provider: 'Qwen',
    input: 'Text / Image',
    output: 'Text',
    inputPrice: '$0.20 / M tokens',
    outputPrice: '$0.88 / M tokens',
    blurb: 'Large Qwen vision-language model for text and image input.',
  },

  // --------------------
  // xAI
  // --------------------
  {
    id: 'xai/grok-4',
    label: 'Grok 4',
    provider: 'xAI',
    input: 'Text / Image',
    output: 'Text',
    inputPrice: '$3.0 / M tokens',
    outputPrice: '$15.0 / M tokens',
    blurb: 'xAI Grok model for multimodal input and text output.',
  },
  {
    id: 'xai/grok-4-fast',
    label: 'Grok 4 Fast',
    provider: 'xAI',
    input: 'Text / Image',
    output: 'Text',
    inputPrice: '$0.20 / M tokens',
    outputPrice: '$0.50 / M tokens',
    blurb: 'Fast xAI Grok model for efficient chat responses.',
  },
  {
    id: 'xai/grok-4.1-fast',
    label: 'Grok 4.1 Fast',
    provider: 'xAI',
    input: 'Text / Image',
    output: 'Text',
    inputPrice: '$0.20 / M tokens',
    outputPrice: '$0.50 / M tokens',
    blurb: 'Updated fast Grok model for text and image input.',
  },

  // --------------------
  // Other
  // --------------------
  {
    id: 'other/glm-5.1',
    label: 'GLM 5.1',
    provider: 'Other',
    input: 'Text',
    output: 'Text',
    inputPrice: '$1.1 / M tokens',
    outputPrice: '$3.5 / M tokens',
    blurb: 'GLM text model for general chat tasks.',
  },
  {
    id: 'other/kimi-k2.5',
    label: 'Kimi K2.5',
    provider: 'Other',
    input: 'Text / Image',
    output: 'Text',
    inputPrice: '$0.40 / M tokens',
    outputPrice: '$2.0 / M tokens',
    blurb: 'Kimi multimodal model for text and image input.',
  },
  {
    id: 'other/glm-4.7',
    label: 'GLM 4.7',
    provider: 'Other',
    input: 'Text',
    output: 'Text',
    inputPrice: '$0.40 / M tokens',
    outputPrice: '$1.8 / M tokens',
    blurb: 'GLM text model for efficient chat generation.',
  },
  {
    id: 'other/glm-4.6',
    label: 'GLM 4.6',
    provider: 'Other',
    input: 'Text',
    output: 'Text',
    inputPrice: '$0.39 / M tokens',
    outputPrice: '$1.9 / M tokens',
    blurb: 'GLM text model for general-purpose responses.',
  },
  {
    id: 'other/minimax-m2.1',
    label: 'MiniMax M2.1',
    provider: 'Other',
    input: 'Text',
    output: 'Text',
    inputPrice: '$0.29 / M tokens',
    outputPrice: '$0.95 / M tokens',
    blurb: 'MiniMax model for text-based chat.',
  },
  {
    id: 'other/minimax-m2.5',
    label: 'MiniMax M2.5',
    provider: 'Other',
    input: 'Text',
    output: 'Text',
    inputPrice: '$0.15 / M tokens',
    outputPrice: '$1.1 / M tokens',
    blurb: 'Low-cost MiniMax model for text responses.',
  },
] as const;

export type ChatModelId = (typeof CHAT_MODEL_OPTIONS)[number]['id'];

export const EMBEDDING_MODEL = 'openai/text-embedding-3-small' as const;